package login;


/**
* login/inicio_sesionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* miércoles 14 de noviembre de 2018 00H22' CET
*/

public interface inicio_sesionOperations 
{
  boolean logear (String user, String pass);
  boolean registrar (String user, String pass);
} // interface inicio_sesionOperations
