package login;

/**
* login/inicio_sesionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* miércoles 14 de noviembre de 2018 00H22' CET
*/

public final class inicio_sesionHolder implements org.omg.CORBA.portable.Streamable
{
  public login.inicio_sesion value = null;

  public inicio_sesionHolder ()
  {
  }

  public inicio_sesionHolder (login.inicio_sesion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = login.inicio_sesionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    login.inicio_sesionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return login.inicio_sesionHelper.type ();
  }

}
