package login;


/**
* login/inicio_sesion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* lunes 19 de noviembre de 2018 19H28' CET
*/

public interface inicio_sesion extends inicio_sesionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface inicio_sesion
