package login;


/**
* login/inicio_sesionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* lunes 19 de noviembre de 2018 19H28' CET
*/

public abstract class inicio_sesionPOA extends org.omg.PortableServer.Servant
 implements login.inicio_sesionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("logear", new java.lang.Integer (0));
    _methods.put ("registrar", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // login/inicio_sesion/logear
       {
         String user = in.read_string ();
         String pass = in.read_string ();
         boolean $result = false;
         $result = this.logear (user, pass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // login/inicio_sesion/registrar
       {
         String user = in.read_string ();
         String pass = in.read_string ();
         boolean $result = false;
         $result = this.registrar (user, pass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:login/inicio_sesion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public inicio_sesion _this() 
  {
    return inicio_sesionHelper.narrow(
    super._this_object());
  }

  public inicio_sesion _this(org.omg.CORBA.ORB orb) 
  {
    return inicio_sesionHelper.narrow(
    super._this_object(orb));
  }


} // class inicio_sesionPOA
